(function () {
  const defaultCare = [
    "Limpiar con pano seco o apenas humedo.",
    "Evitar golpes o caidas.",
    "No sumergir en agua.",
    "Usar en interiores o espacios protegidos.",
  ];

  window.JAZMIN_SEED = {
    categories: [
      {
        id: "macetas",
        name: "Macetas",
        description: "Disenos artesanales para plantas de interior.",
        image: "img/F-.jpg",
        order: 1,
      },
      {
        id: "floreros",
        name: "Floreros",
        description: "Siluetas organicas para mesas, estantes y rincones sutiles.",
        image: "img/C-.jpg",
        order: 2,
      },
      {
        id: "carameleras",
        name: "Carameleras",
        description: "Piezas delicadas para mesas dulces, regalos y eventos.",
        image: "img/B-.jpg",
        order: 3,
      },
      {
        id: "bandejas",
        name: "Bandejas",
        description: "Bases decorativas para perfumes, velas o joyeria.",
        image: "img/D-.jpg",
        order: 4,
      },
      {
        id: "porta-sahumerios",
        name: "Porta sahumerios",
        description: "Objetos serenos para rituales cotidianos y espacios calmos.",
        image: "img/D-.jpg",
        order: 5,
      },
      {
        id: "combos",
        name: "Combos",
        description: "Sets listos para regalar o unificar la deco de un ambiente.",
        image: "img/J-.jpg",
        order: 6,
      },
      {
        id: "por-mayor",
        name: "Venta por mayor",
        description: "Opciones para reventa, souvenirs, tiendas y eventos.",
        image: "img/G-.jpg",
        order: 7,
      },
    ],
    products: [
      {
        id: "p1",
        slug: "maceta-oval-aura",
        name: "Maceta Oval Aura",
        categoryId: "macetas",
        price: 9500,
        shortDescription: "Maceta escultorica de yeso ceramico para plantas de interior.",
        fullDescription:
          "Pieza artesanal de yeso ceramico con borde suave y presencia escultural, pensada para decorar livings, escritorios, mesas de luz o rincones con impronta minimalista.",
        description: "Maceta escultorica de yeso ceramico para plantas de interior.",
        image: "img/H-.jpg",
        gallery: ["img/H-.jpg", "img/C-.jpg", "img/F-.jpg"],
        colors: ["Crema", "Arena", "Rosa viejo", "Gris claro"],
        sizes: ["Chico", "Mediano"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo / funcional",
        personalization: "Consultar colores disponibles",
        idealFor: "Hogar, regalos, souvenirs y emprendimientos",
        care: defaultCare,
        tags: ["Nuevo"],
        featured: true,
        status: "available",
        active: true,
        order: 1,
      },
      {
        id: "p2",
        slug: "florero-luna",
        name: "Florero Luna",
        categoryId: "floreros",
        price: 13200,
        shortDescription: "Florero artesanal de yeso ceramico para flores secas y ramos pequenos.",
        fullDescription:
          "Florero de silueta curva y textura mate, ideal para decorar mesas, estantes, livings o espacios comerciales con una estetica delicada y serena.",
        description: "Florero artesanal de yeso ceramico para flores secas y ramos pequenos.",
        image: "img/C-.jpg",
        gallery: ["img/C-.jpg", "img/F-.jpg", "img/H-.jpg"],
        colors: ["Blanco", "Beige", "Rosa viejo", "Verde agua"],
        sizes: ["Unico"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo",
        personalization: "Consultar colores disponibles",
        idealFor: "Hogar, regalos y rincones especiales",
        care: defaultCare,
        tags: ["Mas vendido"],
        featured: true,
        status: "available",
        active: true,
        order: 2,
      },
      {
        id: "p3",
        slug: "bandeja-lienzo",
        name: "Bandeja Lienzo",
        categoryId: "bandejas",
        price: 11800,
        shortDescription: "Bandeja de yeso para apoyar perfumes, velas y objetos cotidianos.",
        fullDescription:
          "Base rectangular de terminacion prolija, creada para ordenar piezas pequenas y sumar un gesto artesanal a tocadores, mesas ratonas o exhibidores.",
        description: "Bandeja de yeso para apoyar perfumes, velas y objetos cotidianos.",
        image: "img/D-.jpg",
        gallery: ["img/D-.jpg", "img/A-.jpg", "img/J-.jpg"],
        colors: ["Arena", "Blanco roto", "Verde seco"],
        sizes: ["Mediano", "Grande"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo / organizador",
        personalization: "Consultar colores disponibles",
        idealFor: "Hogar, eventos y deco de mesas",
        care: defaultCare,
        tags: ["Ideal regalo"],
        featured: true,
        status: "available",
        active: true,
        order: 3,
      },
      {
        id: "p4",
        slug: "caramelera-nube",
        name: "Caramelera Nube",
        categoryId: "carameleras",
        price: 14500,
        shortDescription: "Caramelera con tapa para mesas dulces y rincones de recepcion.",
        fullDescription:
          "Pieza artesanal de lineas suaves y volumen limpio, pensada para eventos, souvenirs, regalos o espacios donde la deco tambien cumple una funcion.",
        description: "Caramelera con tapa para mesas dulces y rincones de recepcion.",
        image: "img/B-.jpg",
        gallery: ["img/B-.jpg", "img/E-.jpg", "img/G-.jpg"],
        colors: ["Crema", "Rosa viejo", "Amarillo pastel"],
        sizes: ["Unico"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo / funcional",
        personalization: "Consultar colores disponibles",
        idealFor: "Eventos, regalos y mesas dulces",
        care: defaultCare,
        tags: ["Nuevo"],
        featured: false,
        status: "available",
        active: true,
        order: 4,
      },
      {
        id: "p5",
        slug: "porta-sahumerio-brisa",
        name: "Porta sahumerio Brisa",
        categoryId: "porta-sahumerios",
        price: 6900,
        shortDescription: "Base alargada para sahumerios con estilo sobrio y relajado.",
        fullDescription:
          "Porta sahumerio de yeso ceramico de lineas puras, pensado para acompanar rituales diarios y sumar una nota serena a escritorios, repisas o mesas auxiliares.",
        description: "Base alargada para sahumerios con estilo sobrio y relajado.",
        image: "img/D-.jpg",
        gallery: ["img/D-.jpg", "img/J-.jpg", "img/A-.jpg"],
        colors: ["Beige", "Arena", "Verde seco"],
        sizes: ["Unico"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo / funcional",
        personalization: "Consultar colores disponibles",
        idealFor: "Hogar, regalos y espacios de bienestar",
        care: defaultCare,
        tags: [],
        featured: false,
        status: "available",
        active: true,
        order: 5,
      },
      {
        id: "p6",
        slug: "combo-sereno",
        name: "Combo Sereno",
        categoryId: "combos",
        price: 24800,
        shortDescription: "Set coordinado con bandeja, florero y porta sahumerio.",
        fullDescription:
          "Combinacion lista para regalar o ambientar un mismo espacio con lenguaje visual coherente. Reune piezas de yeso ceramico en una paleta suave y versatil.",
        description: "Set coordinado con bandeja, florero y porta sahumerio.",
        image: "img/J-.jpg",
        gallery: ["img/J-.jpg", "img/A-.jpg", "img/D-.jpg"],
        colors: ["Crema", "Arena", "Rosa viejo"],
        sizes: ["Unico"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo / regalo",
        personalization: "Consultar combinaciones disponibles",
        idealFor: "Regalos, hogares y deco integral",
        care: defaultCare,
        tags: ["Ideal regalo"],
        featured: true,
        status: "available",
        active: true,
        order: 6,
      },
      {
        id: "p7",
        slug: "set-mayorista-harmonia",
        name: "Set Mayorista Harmonia",
        categoryId: "por-mayor",
        price: 78000,
        shortDescription: "Pack surtido de 12 piezas para reventa, souvenirs o tiendas.",
        fullDescription:
          "Seleccion mayorista pensada para emprendimientos, tiendas o eventos que buscan piezas prolijas, personalizables y con identidad artesanal consistente.",
        description: "Pack surtido de 12 piezas para reventa, souvenirs o tiendas.",
        image: "img/G-.jpg",
        gallery: ["img/G-.jpg", "img/E-.jpg", "img/B-.jpg"],
        colors: ["Blanco", "Arena", "Rosa viejo", "Gris claro"],
        sizes: ["12 piezas"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo / reventa",
        personalization: "Consultar cantidades, colores y modelos",
        idealFor: "Revendedores, souvenirs y eventos",
        care: defaultCare,
        tags: ["Por mayor"],
        featured: true,
        status: "available",
        active: true,
        order: 7,
      },
      {
        id: "p8",
        slug: "maceta-clara-mini",
        name: "Maceta Clara Mini",
        categoryId: "macetas",
        price: 7200,
        shortDescription: "Maceta pequena para suculentas, cactus y escritorios.",
        fullDescription:
          "Formato compacto de yeso ceramico para plantas chicas y composiciones delicadas. Funciona muy bien en escritorios, mesas de luz o regalos pequenos.",
        description: "Maceta pequena para suculentas, cactus y escritorios.",
        image: "img/F-.jpg",
        gallery: ["img/F-.jpg", "img/C-.jpg", "img/H-.jpg"],
        colors: ["Blanco roto", "Rosa viejo", "Amarillo pastel"],
        sizes: ["Unico", "Chico"],
        material: "Yeso ceramico",
        finish: "Pintado y sellado con barniz",
        style: "Minimalista artesanal",
        use: "Decorativo / funcional",
        personalization: "Consultar colores disponibles",
        idealFor: "Regalos, souvenirs y rincones pequenos",
        care: defaultCare,
        tags: [],
        featured: false,
        status: "out_of_stock",
        active: true,
        order: 8,
      },
    ],
  };
})();
