(function () {
  window.JAZMIN_SEED = {
    categories: [
      {
        id: "macetas",
        name: "Macetas",
        description: "Piezas decorativas para interior con terminacion mate.",
        order: 1,
      },
      {
        id: "floreros",
        name: "Floreros",
        description: "Modelos organicos para flores secas o frescas.",
        order: 2,
      },
      {
        id: "carameleras",
        name: "Carameleras",
        description: "Opciones delicadas para mesas dulces o rincones deco.",
        order: 3,
      },
      {
        id: "bandejas",
        name: "Bandejas",
        description: "Bases artesanales para velas, perfumes o joyeria.",
        order: 4,
      },
      {
        id: "porta-sahumerios",
        name: "Porta sahumerios",
        description: "Disenos suaves para sumar calma a tu espacio.",
        order: 5,
      },
      {
        id: "combos",
        name: "Combos",
        description: "Sets listos para regalar o ambientar.",
        order: 6,
      },
      {
        id: "por-mayor",
        name: "Por mayor",
        description: "Linea para revendedores, tiendas y eventos.",
        order: 7,
      },
    ],
    products: [
      {
        id: "prod-maceta-oval",
        name: "Maceta Oval Aura",
        categoryId: "macetas",
        price: 9500,
        description: "Maceta de yeso con borde suave y presencia escultural.",
        image: "img/maceta-aura.svg",
        gallery: ["img/maceta-aura.svg"],
        colors: ["Crema", "Arena", "Rosa viejo"],
        sizes: ["S", "M"],
        tags: ["Nuevo"],
        status: "available",
        active: true,
        order: 1,
      },
      {
        id: "prod-florero-luna",
        name: "Florero Luna",
        categoryId: "floreros",
        price: 13200,
        description: "Florero con silueta curva para flores secas y ramos pequeños.",
        image: "img/florero-luna.svg",
        gallery: ["img/florero-luna.svg"],
        colors: ["Blanco", "Beige"],
        sizes: ["Unico"],
        tags: ["Mas vendido"],
        status: "available",
        active: true,
        order: 2,
      },
      {
        id: "prod-bandeja-lienzo",
        name: "Bandeja Lienzo",
        categoryId: "bandejas",
        price: 11800,
        description: "Base rectangular para apoyar perfumes, velas o accesorios.",
        image: "img/bandeja-lienzo.svg",
        gallery: ["img/bandeja-lienzo.svg"],
        colors: ["Arena", "Blanco roto"],
        sizes: ["M", "L"],
        tags: [],
        status: "available",
        active: true,
        order: 3,
      },
      {
        id: "prod-caramelera-nube",
        name: "Caramelera Nube",
        categoryId: "carameleras",
        price: 14500,
        description: "Pieza con tapa ideal para mesas de eventos o rincones dulces.",
        image: "img/caramelera-nube.svg",
        gallery: ["img/caramelera-nube.svg"],
        colors: ["Crema", "Rosa viejo"],
        sizes: ["Unico"],
        tags: ["Nuevo"],
        status: "available",
        active: true,
        order: 4,
      },
      {
        id: "prod-sahumerio-brisa",
        name: "Porta sahumerio Brisa",
        categoryId: "porta-sahumerios",
        price: 6900,
        description: "Base alargada de lineas limpias para rituales cotidianos.",
        image: "img/porta-sahumerio-brisa.svg",
        gallery: ["img/porta-sahumerio-brisa.svg"],
        colors: ["Beige", "Arena"],
        sizes: ["Unico"],
        tags: [],
        status: "available",
        active: true,
        order: 5,
      },
      {
        id: "prod-combo-sereno",
        name: "Combo Sereno",
        categoryId: "combos",
        price: 24800,
        description: "Incluye bandeja, florero y porta sahumerio a juego.",
        image: "img/combo-sereno.svg",
        gallery: ["img/combo-sereno.svg"],
        colors: ["Crema", "Arena"],
        sizes: ["Unico"],
        tags: ["Combo"],
        status: "available",
        active: true,
        order: 6,
      },
      {
        id: "prod-mayor-harmonia",
        name: "Set Mayorista Harmonia",
        categoryId: "por-mayor",
        price: 78000,
        description: "Pack de 12 piezas surtidas para tiendas o souvenirs.",
        image: "img/por-mayor-harmonia.svg",
        gallery: ["img/por-mayor-harmonia.svg"],
        colors: ["Blanco", "Arena", "Rosa viejo"],
        sizes: ["12 piezas"],
        tags: ["Por mayor"],
        status: "available",
        active: true,
        order: 7,
      },
      {
        id: "prod-maceta-clara",
        name: "Maceta Clara Mini",
        categoryId: "macetas",
        price: 7200,
        description: "Formato chico para suculentas o mini cactus.",
        image: "img/maceta-clara.svg",
        gallery: ["img/maceta-clara.svg"],
        colors: ["Blanco roto", "Rosa viejo"],
        sizes: ["XS", "S"],
        tags: [],
        status: "out_of_stock",
        active: true,
        order: 8,
      },
    ],
  };
})();
