"""remove_slots_from_availability

Revision ID: 2a29c9f307a0
Revises: d3e8c679b5ca
Create Date: 2025-10-19 12:07:44.077017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a29c9f307a0'
down_revision: Union[str, Sequence[str], None] = 'd3e8c679b5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_availability', 'slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_availability', sa.Column('slots', mysql.SMALLINT(display_width=6), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
